version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - "5434:5432"
    volumes:
        - postgres_data_tasks:/var/lib/postgresql/data
    networks:
      - nestjs-tasks

volumes:
  postgres_data_tasks:
    
networks:
  nestjs-tasks:
     
